services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: VerySecurePassword
      MONGO_INITDB_DATABASE: katarogu
    volumes:
      - ./db-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: VerySecurePassword
      ME_CONFIG_MONGODB_URL: mongodb://root:VerySecurePassword@mongo:27017/katarogu
      ME_CONFIG_BASICAUTH: false