services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: VerySecurePassword
      MONGO_INITDB_DATABASE: katarogu
    volumes:
      - ./docker/db:/data/db

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: VerySecurePassword
      ME_CONFIG_MONGODB_URL: mongodb://root:VerySecurePassword@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  mail:
    container_name: mail
    image: stalwartlabs/mail-server
    tty: true
    stdin_open: true
    ports:
        - 443:443
        - 8080:8080
        - 25:25
        - 587:587
        - 465:465
        - 143:143
        - 993:993
        - 4190:4190
        - 110:110
        - 995:995
    volumes:
        - ./docker/mail:/opt/stalwart-mail

  minio:
    container_name: minio
    image: bitnami/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./docker/minio/data:/bitnami/minio/data
    environment:
      - MINIO_ROOT_USER=katarogu
      - MINIO_ROOT_PASSWORD=VerySecurePassword
      - MINIO_DEFAULT_BUCKETS=public